### PR TITLE
[WIP] Report metric data to Metrics.NET

### PR DESCRIPTION
**Pull request by mikeminutillo**
I included a Trace Report which can be used to replicate the behavior that was already there.

### CODE REVIEW

**Comment by mikeminutillo** [comment]
Need to ILMerge Metrics.NET as it is not strongly named.

**Comment by SzymonPobiega** [comment]
@mikeminutillo I think this is now obsolete and can be closed, right?

**Comment by mikeminutillo** [comment]
Yep. Kill it.

**Comment by SzymonPobiega** [comment]
Replaced by #3 (already merged)

**Pull request closed without merging**
