### PR TITLE
Beta changes

### PR DESCRIPTION
**Pull request by kbaley**
Connects to #56 

For now I'm not targeting netcoreapp2.0 because the dependencies on ServiceControl and Metrics.net are causing problems. Marking as WIP until @Particular/metrics-maintainers have a look.

### CODE REVIEW

**Comment by kbaley** [comment]
I don't know what the approval test is failing. It seems to be a problem reading the metrics assembly but I can't figure out why. Will try to take a look tomorrow with fresh eyes.

**Comment by kbaley** [comment]
Approval tests were failing due to the ILRepack command. I got it going by adding `DebugType` and `DebugSymbols` to the `NServiceBus.Metrics` .csproj file. I don't recall why these need to be removed so let's keep an eye on the builds for the next little while in case they go wonky.

**Comment by Scooletz** [comment]
Am I reading your description correctly @kbaley ?
To get it working and prepared for beta we need to take care of non-dotnetstandard dependencies:
- Metrics.NET
- SC.Monitoring.Data

?

**Comment by kbaley** [comment]
@Scooletz The major goal was to get this working with the new build templates and bring it in line with the other downstreams even if it doesn't support .NET Core yet. It also explicitly marks the assembly as a beta so it can be pushed to nuget.

**Comment by Scooletz** [comment]
So this is only for packaging, right? If this is the case (after reviewing again), I'll be happy to accept it.
I'll be raising a concern related non-standard with the squad responsible for this.

**Comment by Scooletz** [comment]
@kbaley ☝️

**Comment by kbaley** [comment]
@Scooletz Yes it's primarily for packaging and really, that's only the changes to `GitVersion.yml`. The other changes were to bring it in line with https://github.com/Particular/DotNetCoreLaunch/issues/33. These changes aren't strictly necessary but does make it easier for someone else coming in to see things set up similar to other downstreams. But to be clear, the new build templates _will_ work fine with or without this PR.

**Pull request merged**
